config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "messages#index"
  resources :users, only: [:edit, :update]
  resources :rooms, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, category: '--' },
    { id: 2, category: 'ペットショップ' },
    { id: 3, category: '猫カフェ' },
    { id: 4, category: '里親募集' },
    { id: 5, category: 'ご飯'},
    { id: 6, category: 'おもちゃ'},
    { id: 7, category: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :rooms
end

app/models/room.rb
class Room < ApplicationRecord

  validates :category_id, numericality: { other_than: 1 } 

  has_one_attached :image

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :last_name_chinese_characters, :first_name_chinese_characters, :last_name_katakana, :first_name_katakana, :birthday])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def new
    @room = Room.new
  end
  def create
    @room = Room.new(room_params)
    if @room.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def room_params
    params.require(:room).paramit(:comment, :category_id, :image).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nuco</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/index.html.erb
<div class="wrapper">

  <div class="side-bar">
    <div class="side-bar-header">
      <ul class='lists-right'>
        <% if user_signed_in? %>
          <ul class='lists-right'>
            <li><%= link_to current_user.nickname, "#", class: "letter-color" %></li>
            <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "letter-color" %></li>
          </ul>
        <% else %>
          <ul class='lists-right'>
            <li><%= link_to '新規登録', new_user_registration_path, class: "letter-color" %></li>
            <li><%= link_to 'ログイン', new_user_session_path, class: "letter-color" %></li>
          </ul>
        <% end %>
      </ul>
      <%= link_to(new_room_path, class: 'create-room') do %>
        <span class='create-room a'>投稿する</span>
      <% end %>
    </div>
    <div class="rooms">
    </div>
  </div>



  <div class="chat">
    <div class="chat-header">
    </div>
    <div class="messages">
      <div class="message">
        <div class="upper-message">
          <div class="message-user">
            Tom
          </div>
          <div class="message-date">
            2020/3/31(Wed) 12:43:30
          </div>
        </div>
        <div class="lower-message">
          <div class="message-content">
            おはよう
          </div>
        </div>
      </div>
      <div class="message">
        <div class="upper-message">
        <div class="message-user">
          Tom
        </div>
        <div class="message-date">
          2020/3/31(Wed) 12:47:30
        </div>
      </div>
      <div class="lower-message">
        <div class="message-content">
          こんばんは
        </div>
      </div>
    </div>
  </div>
  <div class="form">
  </div>
</div>

app/views/rooms/new.html.erb
<div class="items-sell-contents">

  <header class="items-sell-header">
    <%#= link_to image_tag('1615.png' , size: '185x50'), "/" %>
  </header>
  
  <div class="items-sell-main">
    <h2 class="items-sell-title">投稿内容を入力</h2>
    <%= form_with model: @item, local: true do |f| %>
    <%# 投稿画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        投稿画像
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"room-image" %>
      </div>
    </div>
    <%# 投稿画像 %>
    <div class="items-explain">
        <div class="weight-bold-text">
          投稿文章
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :explanation, class:"items-text", id:"item-info", placeholder:"投稿文章（必須 1,000文字まで）" ,rows:"7" ,maxlength:"1000" %>
      </div>
        <div class="weight-bold-text">
          カテゴリー
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:category_id, Category.all, :id, :category, {}, {class:"select-box",}) %>
        <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "投稿する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>
</div>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>